language: node_js
node_js:
  - stable
deploy:
  provider: heroku
  api_key:
    secure: CS+6dwHPmITK0Ke8hGeznq2uf55KgS+e2jO7iImSz1G6fjWSsowjfKWIREwUpcAOJga0ETabkEazyX4pOQieXE9GfG2v2PIofL2nZeQ7yg5dGkmaZwRNA5eKq6uTriTv20LqOt7hAZmRm3QraYFiXqRzjp5z0ySL7N5ACkXtjufLhxJrAXktOPkYvNnw2nGS5YzBzhRl4iGn8XuzxwODsx0kyHn8OuN76p366ezt4jKvW5sGEn/reN8wIzf60pYZt7wJEyQz1cXfzxqppAQOhK2KB5MlNdOnUDyrG53vlnPOSLc8aycUs9tt9dlzWStrYq7h41vXM4dDdpmMLcZV/SpM591UjxgauGgTmGTYOQtS7caYmNJ+hKoMW+urMSVSTe+ZyZOfJfpD2pPPdhtZDtCO04UXCHSs5wtP/8AmVq1Z2ZMXYGmcRQIeg0P7QEsXTYMUwDLLUsv2Lk8u6xdwpAJbOHQGI+Ztw5/smBIgbXANaxihlupfJz3xTT8C99EmsxiNBIXFeWMFSYXrcvu0UJC5wapjvYnVxPgEJkF5iuSzOnokRcbLKSaaoasYCV7RBUVFMJOtTZ7JcYlU9/+mJ8VSxpJDEWhzq7a5vl25hS5S4+FgwzmqkTxtzL0R7HKrnkCORgQh3ElbZpr0kYdR8bjUAsvBRAwueAEruo/LpBM=
  app:
    master: tomhuhges
    heroku-v2.0: staging-tomhuhges
